services:
  postgres_db:
    image: postgres:16-alpine
    container_name: payment_db
    ports:
    - "5440:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: payment_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: payment_app
    ports:
      - "8000:8000"
    environment:
      DATABASE__DSN: ${DATABASE__DSN}
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      postgres_db: {condition: service_healthy}
      rabbitmq: {condition: service_healthy}

  worker_outbox:
    build: .
    container_name: worker_outbox
    command: ["python", "-m", "workers.outbox"] 
    env_file: .env
    depends_on:
      postgres_db: {condition: service_healthy}
      rabbitmq: {condition: service_healthy}

  worker_payment:
    build: .
    container_name: worker_payment
    command: ["python",  "-m", "workers.payment"]
    env_file: .env
    depends_on:
      postgres_db: {condition: service_healthy}
      rabbitmq: {condition: service_healthy}

volumes:
  postgres_data: