"""init db

Revision ID: 2be224e75d73
Revises:
Create Date: 2026-04-24 18:59:56.709889

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2be224e75d73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'outbox',
        sa.Column('event_type', sa.String(length=100), nullable=False, comment='Тип события'),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Данные события'),
        sa.Column(
            'status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', 'EXHAUSTED', name='outboxstatus'), nullable=False, comment='Статус события'
        ),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='Время успешной обработки'),
        sa.Column('attempts', sa.Integer(), server_default='0', nullable=False, comment='Количество попыток отправки'),
        sa.Column('error', sa.Text(), nullable=True, comment='Последняя ошибка при отправке'),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор UUID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_outbox_status'), 'outbox', ['status'], unique=False)
    op.create_table(
        'payment',
        sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма платежа'),
        sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency'), server_default='RUB', nullable=False, comment='Валюта'),
        sa.Column('description', sa.String(length=255), nullable=True, comment='Описание транзакции'),
        sa.Column('metadata_extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Дополнительная информация'),
        sa.Column(
            'status',
            sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='paymentstatus'),
            server_default='PENDING',
            nullable=False,
            comment='Текущий статус платежа',
        ),
        sa.Column('idempotency_key', sa.String(length=100), nullable=False, comment='Ключ идемпотентности для защиты от дублей'),
        sa.Column('webhook_url', sa.Text(), nullable=False, comment='URL для уведомления о результате'),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время завершения обработки платежа'),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Уникальный идентификатор UUID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
        sa.CheckConstraint("NOT (status IN ('SUCCEEDED', 'FAILED') AND completed_at IS NULL)", name='ck_payment_completion_date_required'),
        sa.CheckConstraint('amount > 0', name='ck_payment_amount_positive'),
        sa.CheckConstraint('char_length(idempotency_key) >= 10', name='ck_payment_idempotency_key_len'),
        sa.CheckConstraint('completed_at >= created_at', name='ck_payment_date_order'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('idempotency_key'),
    )
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_outbox_status'), table_name='outbox')
    op.drop_table('outbox')
    # ### end Alembic commands ###
